### ISSUE TITLE
Attribute error when running UPP

### ISSUE THREAD

**Issue by wasade** [smirarab/sepp#132]
Running UPP without arguments yields an `AttributeError`

```
$ run_upp.py 
[09:27:49] config.py (line 317):  WARNING: Main configuration file was not found at: /home/mcdonadt/miniconda3/envs/qiime2-2023.5/share/sepp/sepp/upp.config
Proceeding without the main configuration...
[09:27:49] config.py (line 349):     INFO: Seed number: 297834
Traceback (most recent call last):
  File "/home/mcdonadt/miniconda3/envs/qiime2-2023.5/bin/run_upp.py", line 25, in <module>
    main()
  File "/home/mcdonadt/miniconda3/envs/qiime2-2023.5/lib/python3.8/site-packages/sepp/exhaustive_upp.py", line 450, in main
    UPPExhaustiveAlgorithm().run()
  File "/home/mcdonadt/miniconda3/envs/qiime2-2023.5/lib/python3.8/site-packages/sepp/exhaustive_upp.py", line 59, in __init__
    ExhaustiveAlgorithm.__init__(self)
  File "/home/mcdonadt/miniconda3/envs/qiime2-2023.5/lib/python3.8/site-packages/sepp/exhaustive.py", line 236, in __init__
    self.strategy = options().exhaustive.strategy
AttributeError: 'Namespace' object has no attribute 'exhaustive'
(qiime2-2023.5) 09:27:49 (dtmcdonald@b2-001):~$ run_upp.py --version
[09:29:20] config.py (line 317):  WARNING: Main configuration file was not found at: /home/mcdonadt/miniconda3/envs/qiime2-2023.5/share/sepp/sepp/upp.config
Proceeding without the main configuration...
run_upp.py 4.3.10
```

**Comment by wasade** [comment]
This was from the installation of `sepp` that comes with QIIME 2, so I'm not sure what's done upstream. @sjanssen2? I think the updates to the bioconda recipe should solve this though

**Comment by sjanssen2** [comment]
When I came up with the bioconda recipe for SEPP, I never intended to support execution of UPP (I considered UPP a separate software). It was @lrauschning who added config creation of UPP to the bioconda recipe. Besides a `run_upp.py --help` there doesn't seem to be any functional testing of UPP, so far.

The latest QIIME2 release requires python 3.8 and SEPP 4.3.10 (this conda package was build prior to @lrauschning modifications). Therefore, I recommend adding a subrecipe to bioconda. However, I realized that UPP depends on pasta, which has no functional bioconda package for python 3.8 yet. My attempts to build one fail so far, due to issues with OSX binaries: https://github.com/bioconda/bioconda-recipes/pull/44543. They are not given as dependencies, but downloaded from specific github repos - not very conda like. It might be worth checking if pasta can be build by using conda shipped programs instead?!

**Comment by wasade** [comment]
cc @dpear

@sjanssen2, any chance you, @dpear, @lrauschning and @yueyujiang could get on a call soon to see if this can all be sorted out?

**Comment by yueyujiang** [comment]
SEPP or UPP works well when I install them from the source code, but I
encountered the same issue when using the bioconda version. I am not sure
how to solve this yet.

**Comment by sjanssen2** [comment]
you may want to have a look here: https://github.com/bioconda/bioconda-recipes/pull/44543 Unfortunately, I was not able to find a solution for the raxml option on OSX on bioconda. My local conda builds run through, though.

**Comment by sjanssen2** [comment]
I am one step closer, as my pasta recipe for bioconda was merged. I am now trying to fix the new sub-recipe (see https://github.com/bioconda/bioconda-recipes/pull/44540) but also the master (see https://github.com/bioconda/bioconda-recipes/pull/44717) recipe `build.sh` commands to recent changes of the build process.

**Comment by wasade** [comment]
That's great!!

**Comment by sjanssen2** [comment]
@wasade and @dpear I could need some help here https://github.com/bioconda/bioconda-recipes/pull/44540 as I don't see the actual blocking error?!

**Comment by wasade** [comment]
Thanks, @sjanssen2. It looks like the build can't be found (https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=47458&view=logs&j=4ca21543-2a5e-5ae4-2a40-dc36939b1512&t=f4f48d5a-1b26-5059-42bb-482003e0a4ce&l=1460) which is puzzling. I see help output from `run_upp.py` higher in the result, and an indication of a zero exit status. I wonder if pinging the bioconda devs may be helpful? They've been responsive on Gitter the few times I've needed to inquire

**Comment by wasade** [comment]
That's great, thanks!! Can this issue be closed then?

**Comment by sjanssen2** [comment]
yes. This issue should be closed @smirarab
